/**
 * LANDEPROFIL: Danmark.
 * =====================
 *
 * Alt landeafhængigt for studentathlete.dk. Et nyt land kopierer DENNE fil,
 * skifter byliste, markører og domæne — motoren røres ikke.
 *
 * `cities` + `countryMarkers` er de to signaler `matchesCountry()` bruger til at
 * afgøre om en roster-atlet hører til landet. `falsePositivePatterns` er de
 * amerikanske steder der ligner (Denmark, SC · Denmark High School) og som
 * ellers ville smugle US-atleter ind.
 */
import type { CountryProfile } from "./types";

const cities: string[] = [
  // Top 50 byer efter befolkning
  "Copenhagen",
  "København",
  "Aarhus",
  "Århus",
  "Odense",
  "Aalborg",
  "Ålborg",
  "Esbjerg",
  "Randers",
  "Kolding",
  "Horsens",
  "Vejle",
  "Roskilde",
  "Herning",
  "Silkeborg",
  "Næstved",
  "Fredericia",
  "Viborg",
  "Køge",
  "Holstebro",
  "Taastrup",
  "Slagelse",
  "Hillerød",
  "Holbæk",
  "Sønderborg",
  "Svendborg",
  "Hjørring",
  "Frederikshavn",
  "Nørresundby",
  "Ringsted",
  "Haderslev",
  "Skive",
  "Sæby",
  "Thisted",
  "Nykøbing Falster",
  "Nykøbing Mors",
  "Helsingør",
  // "Elsinore" (engelsk navn for Helsingør) fjernet — det matcher Lake Elsinore, CA
  // og Elsinore, UT som falske positiver. "Helsingør" er det reelle danske signal.
  "Birkerød",
  "Farum",
  "Frederiksberg",
  "Gentofte",
  "Lyngby",
  "Ballerup",
  "Glostrup",
  "Albertslund",
  "Hvidovre",
  "Brøndby",
  "Ishøj",
  "Greve",
  // 50-100
  "Aabenraa",
  "Åbenrå",
  "Middelfart",
  "Nyborg",
  "Kerteminde",
  "Assens",
  "Faaborg",
  "Rønne",
  "Nakskov",
  "Maribo",
  "Vordingborg",
  "Kalundborg",
  "Sorø",
  "Ribe",
  "Tønder",
  "Varde",
  "Vejen",
  "Brønderslev",
  "Hobro",
  "Grenaa",
  "Grenå",
  "Skanderborg",
  "Hedensted",
  "Ikast",
  "Brande",
  "Struer",
  "Lemvig",
  "Ringkøbing",
  "Skjern",
  "Frederikssund",
  "Frederiksværk",
  "Gilleleje",
  "Hundested",
  "Charlottenlund",
  "Klampenborg",
  "Hellerup",
  "Valby",
  "Vanløse",
  "Brønshøj",
  "Amager",
  "Kastrup",
  "Dragør",
  "Hørsholm",
  "Rudersdal",
  "Allerød",
  "Solrød",
  "Ølstykke",
  "Stenløse",
  "Smørum",
  "Hedehusene",
  "Rødovre",
];

export const dk: CountryProfile = {
  code: "DK",
  language: "da",
  host: "studentathlete.dk",
  brand: "StudentAthlete.dk",
  contactEmail: "info@studentathlete.dk",
  cities,
  countryMarkers: ["Denmark", "Danmark"],
  falsePositivePatterns: [
    /denmark,?\s*(sc|wi|me|ms|tn|ga|al)\b/i,
    /denmark\s+(hs|high|h\.s\.|academy|school|prep)/i,
    /\b(ga|sc|wi|me)\b.*denmark/i,
  ],
};
